apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      containers:
      - name: runner
        image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
        env:
        - name: ACCESS_TOKEN
          value: ${ACCESS_TOKEN}
        - name: ORG_NAME
          value: ministryofjustice-test
        - name: RUNNER_LABELS
          value: operatione-engineering
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          limits:
            cpu: 2
            memory: 512Mi
          requests:
            cpu: 2
            memory: 256Mi 