apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: START_DOCKER_SERVICE
          value: "false"
        - name: ACCESS_TOKEN
          value: ${ACCESS_TOKEN}
        - name: RUNNER_SCOPE
          value: "org"
        - name: ORG_NAME
          value: ministryofjustice-test
        - name: LABELS
          value: operatione-engineering
        - name: RUNNER_NAME_PREFIX
          value: operations-engineering-self-managed-gha-runner
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_WORKDIR
          value: /tmp/github-runner-your-repo
        - name: RUNNER_GROUP
          value: operations-engineering-runners
        - name: RUN_AS_ROOT
          value: 'false'
        resources:
          limits:
            cpu: 2
            memory: 512Mi
          requests:
            cpu: 2
            memory: 256Mi